server:
  port: 18080
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://220.126.62.111:3306/mysql
    username: test01
    password: imsi!@12
    hikari:
      maximum-pool-size: 2
  messages:
    basename: "messages/messages"

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations:
    - classpath*:mapper/**/*.xml
  type-aliases-package: com.project.cmn.mybatis

project:
  access:
    log:
      enabled: true
      filter: true
      aspect: true
  exceptions:
    item-list:
      - name: "ConstraintViolationException"
        status: 400
        res-code: "400"
      - name: "MethodArgumentNotValidException"
        status: 400
        res-code: "400"
      - name: "InvalidValueException"
        status: 400
        res-code: "400"